#
# Autogenerated by Thrift Compiler (0.8.0)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#

require 'thrift'
require 'echo_server_types'

module EchoServer
  class Client
    include ::Thrift::Client

    def echo(msg)
      send_echo(msg)
      return recv_echo()
    end

    def send_echo(msg)
      send_message('echo', Echo_args, :msg => msg)
    end

    def recv_echo()
      result = receive_message(Echo_result)
      return result.success unless result.success.nil?
      raise ::Thrift::ApplicationException.new(::Thrift::ApplicationException::MISSING_RESULT, 'echo failed: unknown result')
    end

  end

  class Processor
    include ::Thrift::Processor

    def process_echo(seqid, iprot, oprot)
      args = read_args(iprot, Echo_args)
      result = Echo_result.new()
      result.success = @handler.echo(args.msg)
      write_result(result, oprot, 'echo', seqid)
    end

  end

  # HELPER FUNCTIONS AND STRUCTURES

  class Echo_args
    include ::Thrift::Struct, ::Thrift::Struct_Union
    MSG = 1

    FIELDS = {
      MSG => {:type => ::Thrift::Types::STRING, :name => 'msg'}
    }

    def struct_fields; FIELDS; end

    def validate
    end

    ::Thrift::Struct.generate_accessors self
  end

  class Echo_result
    include ::Thrift::Struct, ::Thrift::Struct_Union
    SUCCESS = 0

    FIELDS = {
      SUCCESS => {:type => ::Thrift::Types::STRING, :name => 'success'}
    }

    def struct_fields; FIELDS; end

    def validate
    end

    ::Thrift::Struct.generate_accessors self
  end

end

